source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'cukable', :git => 'git://github.com/wapcaplet/cukable.git', :branch => 'multi-app'
gem 'cucumber'
gem 'cucumber-rails'
gem 'sqlite3'
gem 'database_cleaner'
gem 'capybara'

# Asset template engines
gem 'json'
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'
gem 'jquery-rails'

