source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'cucumber'
gem 'cucumber-rails'
gem 'sqlite3'
gem 'database_cleaner'
gem 'capybara'
gem 'cukable', '0.1.2'

# Asset template engines
gem 'json'
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'
gem 'jquery-rails'

